// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vshcmxwholwjwofgftwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzaGNteHdob2x3andvZmdmdHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTkwNzUsImV4cCI6MjA3MTU3NTA3NX0.T94xhr9uFm4j90YM4mpEhDHNoxx-hiqNuAOl_6rSRHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});